language: go
go:
    - 1.9.5
before_script:
    - go get github.com/tcnksm/ghr
    - go get github.com/aktau/github-release
script:
    - cd $HOME/gopath/src/github.com/ggggle/liveGet
    - chmod +x ./make.sh
    - ./make.sh
    - ghr -u ggggle -t $GITHUB_TOKEN -replace master releases/
    - github-release edit -u ggggle -s $GITHUB_TOKEN -r liveGet -t master -n "Ver `cat ver`" -d "`cat changelog`"
    - exit 0
notifications:
    email: false
